local set_hl = vim.api.nvim_set_hl
local base16 = require 'colors.colors'.base16

set_hl(0, 'TSAnnotation', { fg = base16.base0F, sp = "none" })
set_hl(0, 'TSAttribute', { fg = base16.base0A, sp = "none" })
set_hl(0, 'TSCharacter', { fg = base16.base08, sp = "none" })
set_hl(0, 'TSConstBuiltin', { fg = base16.base09, sp = "none" })
set_hl(0, 'TSConstMacro', { fg = base16.base08, sp = "none" })
set_hl(0, 'TSError', { fg = base16.base08, sp = "none" })
set_hl(0, 'TSException', { fg = base16.base08, sp = "none", italic = true })
set_hl(0, 'TSFloat', { fg = base16.base09, sp = "none" })
set_hl(0, 'TSKeywordFunction', { fg = base16.base0E, sp = "none", italic = true })
set_hl(0, 'TSKeywordReturn', { fg = base16.base0E, sp = "none", italic = true })
set_hl(0, 'TSFuncBuiltin', { fg = base16.base0D, sp = "none" })
set_hl(0, 'TSFuncMacro', { fg = base16.base08, sp = "none" })
set_hl(0, 'TSKeywordOperator', { fg = base16.base0E, sp = "none", italic = true })
set_hl(0, 'TSMethod', { fg = base16.base0D, sp = "none" })
set_hl(0, 'TSNamespace', { fg = base16.base07, sp = "none" })
set_hl(0, 'TSNone', { fg = base16.base05, sp = "none" })
set_hl(0, 'TSParameter', { fg = base16.base08, sp = "none" })
set_hl(0, 'TSParameterReference', { fg = base16.base05, sp = "none" })
set_hl(0, 'TSPunctBracket', { fg = base16.base0C })
set_hl(0, 'TSPunctDelimiter', { fg = base16.base0C, sp = "none" })
set_hl(0, 'TSPunctSpecial', { fg = base16.base08, sp = "none" })
set_hl(0, 'TSStringRegex', { fg = base16.base0C, sp = "none" })
set_hl(0, 'TSStringEscape', { fg = base16.base0C, sp = "none" })
set_hl(0, 'TSSymbol', { fg = base16.base0B, sp = "none" })
set_hl(0, 'TSTagDelimiter', { fg = base16.base0F, sp = "none" })
set_hl(0, 'TSText', { fg = base16.base05, sp = "none" })
set_hl(0, 'TSStrong', { bold = true })
set_hl(0, 'TSEmphasis', { fg = base16.base09, sp = "none" })
set_hl(0, 'TSStrike', { fg = base16.base00, sp = "none", strikethrough = true })
set_hl(0, 'TSLiteral', { fg = base16.base09, sp = "none" })
set_hl(0, 'TSURI', { fg = base16.base09, sp = "none", underline = true })
set_hl(0, 'TSTypeBuiltin', { fg = base16.base0E, sp = "none", italic = true })
set_hl(0, 'TSVariableBuiltin', { fg = base16.base05, sp = "none" })
set_hl(0, 'TSVariable', { fg = base16.base05 })
set_hl(0, 'TSDefinition', { sp = base16.base04, underline = true })
set_hl(0, 'TSDefinitionUsage', { sp = base16.base04, underline = true })
set_hl(0, 'TSCurrentScope', { bold = true })
set_hl(0, 'luaTSField', { fg = base16.base0D })
set_hl(0, 'TSFieldKey', { fg = base16.base08 })
set_hl(0, 'TSProperty', { fg = base16.base07 })
set_hl(0, 'TSConstructor', { fg = base16.base0D })

set_hl(0, 'Boolean', { fg = base16.base08, italic = true })
set_hl(0, 'Character', { fg = base16.base08 })
set_hl(0, 'Conditional', { fg = base16.base0E, italic = true })
set_hl(0, 'Constant', { fg = base16.base08 })
set_hl(0, 'Define', { fg = base16.base0E, sp = "none" })
set_hl(0, 'Delimiter', { fg = base16.base0F })
set_hl(0, 'Float', { fg = base16.base09 })
set_hl(0, 'Variable', { fg = base16.base05 })
set_hl(0, 'Function', { fg = base16.base0D })
set_hl(0, 'Identifier', { fg = base16.base08, sp = "none" })
set_hl(0, 'Include', { fg = base16.base0E, italic = true })
set_hl(0, 'Keyword', { fg = base16.base0E, italic = true })
set_hl(0, 'Label', { fg = base16.base0A })
set_hl(0, 'Number', { fg = base16.base08 })
set_hl(0, 'Operator', { fg = base16.base0C })
set_hl(0, 'PreProc', { fg = base16.base0A })
set_hl(0, 'Repeat', { fg = base16.base0E, italic = true })
set_hl(0, 'Special', { fg = base16.base0C })
set_hl(0, 'SpecialChar', { fg = base16.base0F })
set_hl(0, 'Statement', { fg = base16.base08 })
set_hl(0, 'StorageClass', { fg = base16.base0A })
set_hl(0, 'String', { fg = base16.base0B })
set_hl(0, 'Structure', { fg = base16.base0E })
set_hl(0, 'Tag', { fg = base16.base0A })
set_hl(0, 'Todo', { fg = base16.base0A, bg = base16.base01 })
set_hl(0, 'Type', { fg = base16.base07, sp = "none" })
set_hl(0, 'Typedef', { fg = base16.base0A })

set_hl(0, 'ClassDeclaration', { fg = base16.base0B })
set_hl(0, 'InterfaceDeclaration', { fg = '#78ccf0' })
set_hl(0, 'FunctionCall', { fg = base16.base0B })
set_hl(0, 'AttributeParameter', { fg = '#467cda' })
