require 'mapping.comments'
require 'mapping.dap'
require 'mapping.default'
require 'mapping.diffview'
require 'mapping.git'
require 'mapping.lsp'
require 'mapping.nvimtree'
require 'mapping.telescope'
