local colors = require 'colors.colors'

local icon_colors = {
  pink = '#ff75a0',
  vibrant_green = '#7eca9c',
  blue = '#61afef',
  cyan = '#a3b8ef',
  teal = '#519ABA',
}

return {
  { 'DevIconDefault', { fg = colors.base0F } },
  { 'DevIconc', { fg = colors.base0D } },
  { 'DevIconcss', { fg = icon_colors.blue } },
  { 'DevIcondeb', { fg = icon_colors.cyan } },
  { 'DevIconDockerfile', { fg = icon_colors.cyan } },
  { 'DevIconhtml', { fg = colors.base08 } },
  { 'DevIconjpeg', { fg = colors.base0E } },
  { 'DevIconjpg', { fg = colors.base0E } },
  { 'DevIconjs', { fg = colors.base0A } },
  { 'DevIconkt', { fg = colors.base08 } },
  { 'DevIconlock', { fg = colors.base0F } },
  { 'DevIconlua', { fg = icon_colors.blue } },
  { 'DevIconmp3', { fg = colors.base05 } },
  { 'DevIconmp4', { fg = colors.base05 } },
  { 'DevIconout', { fg = colors.base05 } },
  { 'DevIconpng', { fg = colors.base0E } },
  { 'DevIconpy', { fg = icon_colors.cyan } },
  { 'DevIcontoml', { fg = icon_colors.blue } },
  { 'DevIconts', { fg = icon_colors.teal } },
  { 'DevIconttf', { fg = colors.base05 } },
  { 'DevIconrb', { fg = icon_colors.pink } },
  { 'DevIconrpm', { fg = colors.base08 } },
  { 'DevIconvue', { fg = icon_colors.vibrant_green } },
  { 'DevIconwoff', { fg = colors.base05 } },
  { 'DevIconwoff2', { fg = colors.base05 } },
  { 'DevIconxz', { fg = colors.base0A } },
  { 'DevIconzip', { fg = colors.base0A } },
  { 'DevIconZig', { fg = colors.base08 } },
}
