local set_hl = vim.api.nvim_set_hl
local colors = require 'colors.colors'.colors

set_hl(0, 'StatusLine', { bg = colors.black })
set_hl(0, 'St_gitIcons', { fg = colors.light_grey, bg = colors.black, bold = true })
set_hl(0, 'St_lspError', { fg = colors.red, bg = colors.black })
set_hl(0, 'St_lspWarning', { fg = colors.yellow, bg = colors.black })
set_hl(0, 'St_LspHints', { fg = colors.purple, bg = colors.black })
set_hl(0, 'St_LspInfo', { fg = colors.green, bg = colors.black })
set_hl(0, 'St_LspStatus', { fg = colors.nord_blue, bg = colors.black })
set_hl(0, 'St_LspProgress', { fg = colors.green, bg = colors.black })
set_hl(0, 'St_LspStatus_Icon', { fg = colors.black, bg = colors.nord_blue })
set_hl(0, 'St_NormalMode', { bg = colors.nord_blue, fg = colors.black, bold = true })
set_hl(0, 'St_InsertMode', { bg = colors.dark_purple, fg = colors.black, bold = true })
set_hl(0, 'St_TerminalMode', { bg = colors.green, fg = colors.black, bold = true })
set_hl(0, 'St_NTerminalMode', { bg = colors.yellow, fg = colors.black, bold = true })
set_hl(0, 'St_VisualMode', { bg = colors.cyan, fg = colors.black, bold = true })
set_hl(0, 'St_ReplaceMode', { bg = colors.orange, fg = colors.black, bold = true })
set_hl(0, 'St_ConfirmMode', { bg = colors.teal, fg = colors.black, bold = true })
set_hl(0, 'St_CommandMode', { bg = colors.green, fg = colors.black, bold = true })
set_hl(0, 'St_SelectMode', { bg = colors.nord_blue, fg = colors.black, bold = true })
set_hl(0, 'St_EmptySpace', { fg = colors.grey, bg = colors.lightbg })
set_hl(0, 'St_EmptySpace2', { fg = colors.grey, bg = colors.black })
set_hl(0, 'St_file_info', { bg = colors.lightbg, fg = colors.white })
set_hl(0, 'St_file_sep', { bg = colors.black, fg = colors.lightbg })
set_hl(0, 'St_cwd_text', { fg = colors.light_grey, bg = colors.black })
set_hl(0, 'St_DapStatus', { fg = colors.green, bg = colors.black })
